apiVersion: v1
kind: Service
metadata:
  name: svc-cord
  labels:
    app: svc-cord
spec:
  selector:
    app: svc-cord
  ports:
    - name: grpc-port
      protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP
