apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-app
  labels:
    app: login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-app
  template:
    metadata:
      labels:
        app: login-app
    spec:
      containers:
      - name: login-app
        image: rithwwik/login-app:latest
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: login-app
  labels:
    app: login-app
spec:
  type: ClusterIP
  selector:
    app: login-app
  ports:
  - protocol: TCP
    port: 3005
    targetPort: 3005
