apiVersion: v1
kind: Service
metadata:
  name: svc-did
  labels:
    app: svc-did
spec:
  selector:
    app: svc-did
  ports:
    - name: grpc-port
      protocol: TCP
      port: 50053
      targetPort: 50053
  type: ClusterIP
